{{- if eq .Values.database.type "cnpg" }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "valtimo-demo.cnpg.clusterName" . }}
  labels:
    {{- include "valtimo-demo.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.database.cnpg.instances }}

  postgresql:
    {{- with .Values.database.cnpg.parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end }}

  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.database.cnpg.postgresVersion }}

  bootstrap:
    initdb:
      database: {{ .Values.database.cnpg.database }}
      owner: {{ .Values.database.cnpg.owner }}

  storage:
    size: {{ .Values.database.cnpg.storage.size }}
    {{- if .Values.database.cnpg.storage.storageClass }}
    storageClass: {{ .Values.database.cnpg.storage.storageClass }}
    {{- end }}

  {{- with .Values.database.cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
