apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valtimo-demo.frontend.fullname" . }}-nginx
  labels:
    {{- include "valtimo-demo.frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        gzip on;
        gzip_proxied any;
        gzip_buffers 16 8k;
        gzip_types    text/plain application/javascript application/x-javascript text/javascript text/xml text/css;
        gzip_vary on;

        location ~ /(api|management|v3|mock-api) {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://{{ include "valtimo-demo.backend.fullname" . }}:{{ .Values.backend.service.port }};
        }

        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html?$args;
        }
    }
